name: vulture
channels:
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - pytorch>=2.0.0
  - pytorch-cuda>=12.4.0
  - conda-forge::cudatoolkit
  - torchvision
  - torchmetrics>=0.10.3
  - pip
  - pip:
      - ninja
      - packaging
      - omegaconf>=2.3.0
      - omegaconf>=2.3.0
      - segmentation_models_pytorch
      - albumentations
      - interactive-seg-backend@git+https://github.com/tldr-group/interactive-seg-backend
      - featup@git+https://github.com/mhamilton723/FeatUp
      - pretrained_microscopy_models@git+https://github.com/nasa/pretrained-microscopy-models
