name: vulture
channels:
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - pytorch>=2.0.0
  - pytorch-cuda>=12.4.0
  - conda-forge::cudatoolkit
  - torchvision
  - torchmetrics>=0.10.3
  - pip
  - pip:
      - ninja
      - packaging
      - interactive-seg-backend@git+https://github.com/tldr-group/interactive-seg-backend
